version: "3.9"

services:
  backend:
    build:
      context: ./api
    container_name: flask-api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      # - DB_HOST=db
      # - DB_PORT=3306
      # - DB_USER=root
      # - DB_PASSWORD=root
      # - DB_NAME=smd_db
    # depends_on:
    #   - db

#   db:
#     image: mysql:8.0
#     container_name: mysql-db
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: smd_db
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data:
